add yaml for transferring nasa amsua to clean bucket
NOAA-PSL/observation-archive pull request #50
Opened 2023-01-09 18:32 UTC by jrknezha

YAML file to be run for transferring nasa amsua data to clean bucket

2023-01-09 21:50 UTC, frolovsa requested changes
Thank you @jrknezha for working on this file. I made some suggestions. I gave you a suggestion for the test path you can use to copy a couple of test files. I think the file as is would crash. 

You can do testing from your personal computer. But i will reboot the aws machine with your rsa key today or tomorrow. please ping me if i forget.

2023-01-09 21:50 UTC, frolovsa commented on data-tree/reanalysis/amsua/nasa/1998-2009.clean-bucket.yaml
> +logging:
you will need to add this line here
`  remove: "log/{dtg}-remove.log"`
can you also add it to the template directory?

2023-01-09 21:50 UTC, frolovsa commented on data-tree/reanalysis/amsua/nasa/1998-2009.clean-bucket.yaml
> +cycling_interval: 21600
you will need to add this line here: 
`remove source file: false`

2023-01-09 21:50 UTC, frolovsa commented on data-tree/reanalysis/amsua/nasa/1998-2009.clean-bucket.yaml
> +    bucket: noaa-nasa-share
is think this is the full path to the bucket
na-stage.us-east-2.noaa-nasa-share

2023-01-09 21:50 UTC, frolovsa commented on data-tree/reanalysis/amsua/nasa/1998-2009.clean-bucket.yaml
> +  path: "observations/reanalysis/amsua/nasa/%Y/%m/bufr/"
you can use this path for testing if you want. 
`observations/reanalysis-test/`
Looking at your file. i dont think it would have ran

2023-01-19 18:47 UTC, jrknezha commented
Updated to transfer from the scratch area that I will manually upload the data too. Added in the remove line to the templates.

2023-01-19 18:48 UTC, jrknezha commented
@frolovsa ready for your review again

2023-01-19 22:31 UTC, frolovsa approved these changes
@jrknezha this looks very good. I made a very small suggestion for the target path.

2023-01-19 22:31 UTC, frolovsa commented on data-tree/reanalysis/amsua/nasa/1998-2009.clean-bucket.yaml
> +  path: "observations/reanalysis/amsua/nasa/%Y/%m/bufr/"
how about we make the destination (i added r21c_repro to the path)
observations/reanalysis/amsua/nasa/r21c_repro/%Y/%m/bufr/

2023-01-24 15:33 UTC, merged